# Generated by Django 3.2.8 on 2021-10-22 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211022_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('membership', 'Membership'), ('product', 'Product')], max_length=10),
        ),
    ]
