# Generated by Django 3.2.8 on 2021-11-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211022_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
