# Generated by Django 3.2.8 on 2021-11-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211105_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
