# Generated by Django 3.2.8 on 2021-11-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_orderitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.AddField(
            model_name='membership',
            name='period_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='period_type',
            field=models.CharField(choices=[('m', 'Month'), ('y', 'Year')], default='y', max_length=1),
            preserve_default=False,
        ),
    ]
