# Generated by Django 3.2.8 on 2021-11-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211112_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='name',
        ),
    ]
